### PR TITLE
Added a very basic test suite

### PR DESCRIPTION
**Pull request by nmav**

### CODE REVIEW

**Comment by nmav** [comment]
This requires autoreconf to be run. It also uncovered the regression in the other patch.

**Comment by arr2036** [comment]
Could you add the make target to .travis.yml so the tests are run as part of CIT

**Comment by nmav** [comment]
The test suite requires a freeradius server to be run as root (or to be present somewhere all the time). If that is available I think it can be automated.

**Comment by arr2036** [comment]
Yes, travis can install the freeradius packages. It'd then need to copy a minimal virtual server into place and start the daemon. In the default config there's a client for 127.0.0.1 with secret testing123.

**Comment by nmav** [comment]
That's nice. In that case could I have two users with the following config?

test    Cleartext-Password := "test"
        Service-Type = Framed-User,
        Framed-Protocol = PPP,
        Framed-Route = 192.168.100.5/24,
        Framed-Route = 192.168.1.0/8,
        Framed-IP-Address = 192.168.1.190,
        Framed-IP-Netmask = 255.255.255.0,
        Framed-Routing = Broadcast-Listen,
        Framed-MTU = 1500,

test6   Cleartext-Password := "test"
        Service-Type = Framed-User,
        Framed-Protocol = PPP,
        Framed-Route = 192.168.100.5/24,
        Framed-Route = 192.168.1.0/8,
        Framed-IPv6-Prefix = "2000:0:0:106::/64",
        Framed-IP-Address = 192.168.1.190,
        Framed-IP-Netmask = 255.255.255.0,
        Framed-Routing = Broadcast-Listen,
        Framed-MTU = 1500,

**Comment by arr2036** [comment]
Yes though for simplicity i'd just use unlang

```
if (User-Name == 'test') {
	update control {
		Cleartext-Password := 'yest'
	}
	update reply {
		Service-Type = Framed-User
		Framed-Protocol = PPP
		Framed-Route := '192.168.100.5/24'
		Framed-Route += '192.168.1.0/8'
		Framed-IP-Address = 192.168.1.190
		Framed-IP-Netmask = 255.255.255.0
		Framed-Routing = Broadcast-Listen
		Framed-MTU = 1500
	}
}
```

**Comment by nmav** [comment]
Hi, is your reply some action point for me? If it is I don't quite understand it.

**Comment by arr2036** [comment]
I can't see any tests being run in the travis output, but maybe I missed something. Could you point to a line in the travis log that indicates test success/failure?

https://travis-ci.org/FreeRADIUS/freeradius-client/builds/55665611

**Comment by nmav** [comment]
autoreconf has to be run for the make check to be available.

**Comment by nmav** [comment]
(I don't run it because Alan does use an old version of it and there many differences in their output)

**Comment by arr2036** [comment]
as a lot of these pull requests need autoreconf to be run, it might be a good idea to add it to travis, else new pull requests may fail travis

**Comment by nmav** [comment]
Nice, at least it fails now. It cannot authenticate as test with password test.

**Comment by nmav** [comment]
(btw if the server also listens on ::1 we can test IPv6 support also)

**Comment by nmav** [comment]
Do you think there is an issue with the test suite or with the server? Can you authenticate with user 'test' and passwd 'test' on the local server? Does the local server listen on '::1' in addition to 127.0.0.1?

**Comment by arr2036** [comment]
No by default it'll only listen on 127.0.0.1. I think 2.1.12 does support it, but radiusd.conf will have to be modifier or overwritten by the test suite.

**Comment by nmav** [comment]
Ok, so if I understand well I should disable the IPv6 check. About the users, are they configured in the travis machine?

**Comment by arr2036** [comment]
The default config isn't sufficient, you should overwrite the users file with one that contains the test users. You should overwrite radiusd.conf with one that has an IPv6 listen block, then restart the server. This can be done in the ``before_script`` actions.

**Comment by nmav** [comment]
I have no idea how to do that as I don't know what the current files hold
nor how to restart the server after overwriting them.

**Comment by arr2036** [comment]
``/etc/init.d/freeradius restart``

https://github.com/FreeRADIUS/freeradius-server/blob/v2.x.x/raddb/users
https://github.com/FreeRADIUS/freeradius-server/blob/v2.x.x/raddb/radiusd.conf.in#L310

Ignore the comment about not being able to use both at the same time, you just need to add:

```
listen {
	ipv6addr = ::
	port = 0
	type = auth
}
```

Those files are installed under ``/etc/freeradius`` by the package. So the users file would be at ``/etc/freeradius/users`` and ``radiusd.conf`` would be at ``/etc/freeradius/radiusd.conf``.

For simplicity, i'd just append the listen section above to ``radiusd.conf`` and ``cp`` a test users file with the test users, over ``/etc/freeradius/users``.

**Comment by nmav** [comment]
I'm not sure how this can be done. Does the travis instance run as root? Should I add these files to freeradius-client git?

**Comment by nmav** [comment]
ping. Should we separate the travis from the test suite? I think the communication is way to slow (also because of my part) to have any result with travis.

**Comment by nmav** [comment]
I finally read the travis documentation and got it to work. Everything is ok except, the IPv6 check which is partial. For some reason freeradius doesn't listen on ::1 (maybe there is no IPv6 support in the travis system).

**Pull request merged**
