### PR TITLE
Auto-generate development manpages based on source description

### PR DESCRIPTION
**Pull request by nmav**
This patch set auto-generates manpages from source code description.
It also includes the auto-generated files.

### CODE REVIEW

**Comment by arr2036** [comment]
We use doxygen for the main server, which has significantly more functions documented. Please could you redo this pull request with doxygen headers.

**Comment by nmav** [comment]
doxygen doesn't generate manpages, gdoc is more powerful.

**Comment by arr2036** [comment]
No, you're wrong. http://www.stack.nl/~dimitri/doxygen/manual/starting.html#man_out

**Comment by nmav** [comment]
It's a petty this wasn't merged, I'm not adding doxygen support, so we are stuck with bad comments instead of better comments. I'll try to rebase my branch on the current comments in freeradius-clients.

**Comment by arr2036** [comment]
When you don't consult with the project maintainers the result is wasted effort.

**Comment by nmav** [comment]
Thanks for that.

**Comment by arr2036** [comment]
The majority of it would be simple search/replace. If you're not willing to do it, I'll take a look tomorrow (please leave the branch in your repo).

We should be working towards convergence between the PAM module, the apache module, this library and the FreeRADIUS decoder/encoder. Using the same code style, system functions, and documentation tools will help with that.

**Pull request closed without merging**
