### PR TITLE
This patch set simplifies string handling

### PR DESCRIPTION
**Pull request by nmav**

### CODE REVIEW

**Comment by nmav** [comment]
Hi, Is there anything I can do to help the adoption of this pull request? This and the conversion to gdoc are the current blockers in order to submit pull requests with the IPv6 patch set.

**Comment by alandekok** [comment]
I think the thing to do is to remove the auto-generated files, pull in all of the patches, and then re-generate the auto-generated files.

As noted in my comments on your fork of the repo, I was *completely* unable to build it due to the lack of a "configure" script.  So there's a hard requirement that the repo contain these files.

However, for short-term merges, it's OK to remove them.

**Comment by nmav** [comment]
> I think the thing to do is to remove the auto-generated files, pull in all of the patches, and then re-generate the auto-generated files.

I believe I can send pull requests on this repository without removing the auto-generated files. It would only require regenerating them at on certain intervals.

> As noted in my comments on your fork of the repo, I was completely unable to build it due to the lack of a "configure" script. So there's a hard requirement that the repo contain these files.

I could help with that if you send the output of autoreconf -fvi.

**Comment by alandekok** [comment]
On Jan 6, 2015, at 2:22 PM, Nikos Mavrogiannopoulos <notifications@github.com> wrote:
> I believe I can send pull requests on this repository without removing the auto-generated files. It would only require regenerating them at on certain intervals.

  That works.

> I could help with that if you send the output of autoreconf -fvi.

  I’ll try to get to that today.=

**Comment by nmav** [comment]
>> I can send pull requests on this repository without removing the auto-generated files. It would only 
>> require regenerating them at on certain intervals.
>That works.

Just to be clear. I could only make new pull requests, if this pull request and the gdoc transition of comments (pull/31) is applied. Otherwise there are way to many conflicts.

**Pull request merged**
