### PR TITLE
Support connections in IPv6 servers

### LINKED ISSUE #42: No IPv6 support in radiusclient library
That's 2015 and IPv6 support is no luxury but a requirement for a library.

As I've previously mentioned, I have a patch set for it which depends on my existing 3 pull requests being merged. If you have no resources for them I volunteer to get that into freeradius-client, towards a 1.2.0 release.

### PR DESCRIPTION
**Pull request by nmav**
This set of patches adds support for connections to IPv6 servers. To simplify the library all legacy IPv4-only functions were dropped.

Resolves #42

### CODE REVIEW

**Comment by nmav** [comment]
(the patch requires autoreconf to be run since new files were added)

**Comment by nmav** [comment]
Any comments on the patches?

**Comment by alandekok** [comment]
I think they're mostly OK.  I just need to find time to read them in detail.

If there's been no progress in a week, I'll probably just merge the changes as-is.

**Comment by nmav** [comment]
Ok, thanks. My next patch set after this is merged, will be a test suite to verify that basic functionality works and avoid regressions on it.

**Comment by nmav** [comment]
ping

**Pull request merged**
